node {
   def commit_id
    environment {
        HOME = '.'
    }
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh'npm config set registry http://registry.npmjs.org/  '
       sh 'npm install --only=dev'
      // sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://registry.hub.docker.com/', 'dockerhub') {
       def app = docker.build("sasankchekuri/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
